/**
 * Rich Music Catalog Data
 * Comprehensive collection of Tracks, Movies, Artists, and Albums
 * with weighted mood tags, acoustic profiles, and multi-relational references.
 */

const { MOODS } = require('./musicTaxonomy');

const movies = [
  {
    id: "movie_dhurandhar",
    title: "Dhurandhar",
    normalizedTitle: "dhurandhar",
    year: 2025,
    releaseDate: "2025-10-18",
    director: "Aditya Dhar",
    musicDirectors: ["Shashwat Sachdev", "Pritam"],
    bannerUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
    description: "High-octane national security action thriller featuring an adrenaline-pumping, soul-stirring soundtrack.",
    trackIds: ["track_dhurandhar_title", "track_dhurandhar_jazbaat", "track_dhurandhar_aag"]
  },
  {
    id: "movie_animal",
    title: "Animal",
    normalizedTitle: "animal",
    year: 2023,
    releaseDate: "2023-12-01",
    director: "Sandeep Reddy Vanga",
    musicDirectors: ["Pritam", "JAM8", "Vishal Mishra", "Shreyas Puranik", "Manan Bhardwaj"],
    bannerUrl: "https://c.saavncdn.com/092/ANIMAL-Hindi-2023-20231124191438-500x500.jpg",
    description: "Blockbuster psychological action drama with an intense multi-genre soundtrack.",
    trackIds: ["track_satranga", "track_hua_main", "track_arjan_vailly"]
  },
  {
    id: "movie_kabir_singh",
    title: "Kabir Singh",
    normalizedTitle: "kabir singh",
    year: 2019,
    releaseDate: "2019-06-21",
    director: "Sandeep Reddy Vanga",
    musicDirectors: ["Mithoon", "Amaal Mallik", "Vishal Mishra", "Sachet-Parampara", "Akhil Sachdeva"],
    bannerUrl: "https://c.saavncdn.com/352/Kabir-Singh-Hindi-2019-20240130132014-500x500.jpg",
    description: "Raw romantic drama with unforgettable chart-topping anthems of love, passion, and heartbreak.",
    trackIds: ["track_bekhayali", "track_tujhe_kitna", "track_tera_ban_jaunga"]
  },
  {
    id: "movie_aashiqui_2",
    title: "Aashiqui 2",
    normalizedTitle: "aashiqui 2",
    year: 2013,
    releaseDate: "2013-04-26",
    director: "Mohit Suri",
    musicDirectors: ["Mithoon", "Ankit Tiwari", "Jeet Gannguli"],
    bannerUrl: "https://c.saavncdn.com/264/Aashiqui-2-Hindi-2013-500x500.jpg",
    description: "A defining romantic masterpiece that ushered in a golden era of modern Bollywood ballads.",
    trackIds: ["track_tum_hi_ho", "track_sunn_raha_hai", "track_chahun_main"]
  },
  {
    id: "movie_shershaah",
    title: "Shershaah",
    normalizedTitle: "shershaah",
    year: 2021,
    releaseDate: "2021-08-12",
    director: "Vishnuvardhan",
    musicDirectors: ["Tanishk Bagchi", "B Praak", "Jasleen Royal", "Javed-Mohsin"],
    bannerUrl: "https://c.saavncdn.com/238/Shershaah-Original-Motion-Picture-Soundtrack-Hindi-2021-20210815181610-500x500.jpg",
    description: "Biographical war drama celebrating Captain Vikram Batra with patriotic and romantic melodies.",
    trackIds: ["track_raataan_lambiyan", "track_ranjha"]
  },
  {
    id: "movie_brahmastra",
    title: "Brahmāstra: Part One – Shiva",
    normalizedTitle: "brahmastra",
    year: 2022,
    releaseDate: "2022-09-09",
    director: "Ayan Mukerji",
    musicDirectors: ["Pritam"],
    bannerUrl: "https://c.saavncdn.com/007/Brahmastra-Hindi-2022-20221006180034-500x500.jpg",
    description: "Mythological fantasy epic with grandiose anthems and soulful romance.",
    trackIds: ["track_kesariya", "track_deva_deva"]
  },
  {
    id: "movie_ddlj",
    title: "Dilwale Dulhania Le Jayenge",
    normalizedTitle: "dilwale dulhania le jayenge",
    year: 1995,
    releaseDate: "1995-10-20",
    director: "Aditya Chopra",
    musicDirectors: ["Jatin-Lalit"],
    bannerUrl: "https://c.saavncdn.com/264/Dilwale-Dulhania-Le-Jayenge-Hindi-1995-500x500.jpg",
    description: "Timeless 90s romance iconic across generations worldwide.",
    trackIds: ["track_tujhe_dekha_toh"]
  }
];

const artists = [
  {
    id: "artist_arijit_singh",
    name: "Arijit Singh",
    normalizedName: "arijit singh",
    aliases: ["arijit", "arjit", "arjit singh"],
    genre: "Bollywood Romantic",
    genres: ["Bollywood Romantic", "Bollywood Melodic", "Sufi"],
    monthlyListeners: 42500000,
    followers: 9800000,
    bio: "Iconic playback singer celebrated for emotive voice and unforgettable romantic anthems across Bollywood.",
    avatarUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80",
    topTracks: ["track_hawayein", "track_tum_hi_ho", "track_agar_tum", "track_kesariya", "track_satranga", "track_apna_bana_le"],
    albums: ["album_brahmastra", "album_aashiqui_2", "album_bhediya"]
  },
  {
    id: "artist_pritam",
    name: "Pritam",
    normalizedName: "pritam",
    aliases: ["pritam chakraborty"],
    genre: "Bollywood Composer",
    genres: ["Bollywood Melodic", "Bollywood Party", "Bollywood Romantic"],
    monthlyListeners: 36000000,
    followers: 6700000,
    bio: "Ace composer behind the soundtrack of modern Indian youth, spanning legendary rom-coms and epics.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80",
    topTracks: ["track_kesariya", "track_hawayein", "track_shayad", "track_khairiyat"],
    albums: ["album_brahmastra", "album_love_aaj_kal"]
  },
  {
    id: "artist_shreya_ghoshal",
    name: "Shreya Ghoshal",
    normalizedName: "shreya ghoshal",
    aliases: ["shreya", "shreya ghosal"],
    genre: "Bollywood Romantic",
    genres: ["Bollywood Melodic", "Classical", "Indian Pop"],
    monthlyListeners: 31000000,
    followers: 8200000,
    bio: "Multi-National Award-winning melody queen known for crystalline pitch and sublime vocal versatility.",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
    topTracks: ["track_agar_tum"],
    albums: []
  },
  {
    id: "artist_diljit_dosanjh",
    name: "Diljit Dosanjh",
    normalizedName: "diljit dosanjh",
    aliases: ["diljit"],
    genre: "Punjabi Pop",
    genres: ["Punjabi Pop", "Bhangra", "Urban Punjabi"],
    monthlyListeners: 24000000,
    followers: 7800000,
    bio: "Global Punjabi icon blending traditional folk cadence with high-fashion contemporary pop.",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80",
    topTracks: ["track_lover", "track_born_to_shine"],
    albums: ["album_moonchild_era"]
  },
  {
    id: "artist_ap_dhillon",
    name: "AP Dhillon",
    normalizedName: "ap dhillon",
    aliases: ["ap", "amritpal singh dhillon"],
    genre: "Punjabi Hip-Hop",
    genres: ["Punjabi Hip-Hop", "Brown Munde", "Trap"],
    monthlyListeners: 19500000,
    followers: 5200000,
    bio: "Pioneering artist behind the international surge of smooth Indo-Western synth-trap.",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80",
    topTracks: ["track_brown_munde"],
    albums: []
  },
  {
    id: "artist_anuv_jain",
    name: "Anuv Jain",
    normalizedName: "anuv jain",
    aliases: ["anuv"],
    genre: "Indie Acoustic",
    genres: ["Indie Acoustic", "Indie Folk"],
    monthlyListeners: 12500000,
    followers: 3400000,
    bio: "Indie singer-songwriter whose heartfelt acoustic guitar and raw lyrical storytelling captivated millions.",
    avatarUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80",
    topTracks: ["track_husn", "track_baarishein"],
    albums: []
  },
  {
    id: "artist_the_weeknd",
    name: "The Weeknd",
    normalizedName: "the weeknd",
    aliases: ["abel tesfaye", "weeknd"],
    genre: "Synthwave / R&B",
    genres: ["Synthwave", "Contemporary R&B", "Electropop"],
    monthlyListeners: 105000000,
    followers: 18500000,
    bio: "Global sensation bridging dark R&B, cinematic synthwave, and blockbuster pop masterpieces.",
    avatarUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80",
    topTracks: ["track_starboy", "track_blinding_lights"],
    albums: ["album_starboy", "album_after_hours"]
  },
  {
    id: "artist_dua_lipa",
    name: "Dua Lipa",
    normalizedName: "dua lipa",
    aliases: ["dua"],
    genre: "Nu-Disco Pop",
    genres: ["Nu-Disco Pop", "Dance Pop"],
    monthlyListeners: 78000000,
    followers: 14200000,
    bio: "British pop powerhouse redefining disco and modern electronic dance-pop.",
    avatarUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    topTracks: ["track_levitating"],
    albums: ["album_future_nostalgia"]
  }
];

const albums = [
  {
    id: "album_dhurandhar",
    title: "Dhurandhar (Original Soundtrack)",
    normalizedTitle: "dhurandhar original soundtrack",
    artist: "Shashwat Sachdev, Pritam",
    year: 2025,
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
    trackIds: ["track_dhurandhar_title", "track_dhurandhar_jazbaat", "track_dhurandhar_aag"],
    movieId: "movie_dhurandhar"
  },
  {
    id: "album_brahmastra",
    title: "Brahmāstra: Part One – Shiva",
    normalizedTitle: "brahmastra part one shiva",
    artist: "Pritam, Arijit Singh",
    year: 2022,
    coverUrl: "https://c.saavncdn.com/007/Brahmastra-Hindi-2022-20221006180034-500x500.jpg",
    trackIds: ["track_kesariya"],
    movieId: "movie_brahmastra"
  },
  {
    id: "album_aashiqui_2",
    title: "Aashiqui 2",
    normalizedTitle: "aashiqui 2",
    artist: "Mithoon, Ankit Tiwari, Jeet Gannguli",
    year: 2013,
    coverUrl: "https://c.saavncdn.com/264/Aashiqui-2-Hindi-2013-500x500.jpg",
    trackIds: ["track_tum_hi_ho"],
    movieId: "movie_aashiqui_2"
  },
  {
    id: "album_kabir_singh",
    title: "Kabir Singh",
    normalizedTitle: "kabir singh",
    artist: "Sachet-Parampara, Mithoon, Akhil Sachdeva",
    year: 2019,
    coverUrl: "https://c.saavncdn.com/352/Kabir-Singh-Hindi-2019-20240130132014-500x500.jpg",
    trackIds: ["track_bekhayali", "track_tujhe_kitna", "track_tera_ban_jaunga"],
    movieId: "movie_kabir_singh"
  }
];

const tracks = [
  // 1. Hawayein
  {
    id: "track_hawayein",
    title: "Hawayein",
    normalizedTitle: "hawayein",
    artist: "Arijit Singh, Pritam",
    artists: ["Arijit Singh", "Pritam"],
    artistIds: ["artist_arijit_singh", "artist_pritam"],
    album: "Jab Harry Met Sejal",
    albumId: "album_jhms",
    movie: "Jab Harry Met Sejal",
    movieId: "movie_jhms",
    year: 2017,
    releaseDate: "2017-07-26",
    durationMs: 290000,
    durationSec: 290,
    coverUrl: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Romantic", "Indian Music"],
    subgenre: "Bollywood Romantic",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ROMANTIC]: 0.95,
      [MOODS.EMOTIONAL]: 0.82,
      [MOODS.CHILL]: 0.70,
      [MOODS.NOSTALGIC]: 0.65
    },
    acousticFeatures: {
      energy: 0.52,
      valence: 0.68,
      danceability: 0.54,
      acousticness: 0.58,
      instrumentalness: 0.02,
      tempo: 98,
      popularity: 0.94
    },
    playsCount: 5200000,
    likesCount: 420000,
    isLiked: true,
    lyrics: "Hawayein hawayein mujhko baha le jayein...",
    explicit: false
  },
  // 2. Agar Tum Saath Ho
  {
    id: "track_agar_tum",
    title: "Agar Tum Saath Ho",
    normalizedTitle: "agar tum saath ho",
    artist: "Arijit Singh, Alka Yagnik, A.R. Rahman",
    artists: ["Arijit Singh", "Alka Yagnik", "A.R. Rahman"],
    artistIds: ["artist_arijit_singh"],
    album: "Tamasha",
    albumId: "album_tamasha",
    movie: "Tamasha",
    movieId: "movie_tamasha",
    year: 2015,
    releaseDate: "2015-10-27",
    durationMs: 341000,
    durationSec: 341,
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Romantic", "Bollywood Sad"],
    subgenre: "Bollywood Sad",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ROMANTIC]: 0.88,
      [MOODS.SAD]: 0.85,
      [MOODS.EMOTIONAL]: 0.95,
      [MOODS.MELANCHOLY]: 0.80
    },
    acousticFeatures: {
      energy: 0.44,
      valence: 0.35,
      danceability: 0.46,
      acousticness: 0.72,
      instrumentalness: 0.01,
      tempo: 88,
      popularity: 0.96
    },
    playsCount: 6800000,
    likesCount: 590000,
    isLiked: true,
    lyrics: "Pal bhar thehar jaao dil ye sambhal jaaye...",
    explicit: false
  },
  // 3. Tum Hi Ho
  {
    id: "track_tum_hi_ho",
    title: "Tum Hi Ho",
    normalizedTitle: "tum hi ho",
    artist: "Arijit Singh, Mithoon",
    artists: ["Arijit Singh", "Mithoon"],
    artistIds: ["artist_arijit_singh"],
    album: "Aashiqui 2",
    albumId: "album_aashiqui_2",
    movie: "Aashiqui 2",
    movieId: "movie_aashiqui_2",
    year: 2013,
    releaseDate: "2013-03-23",
    durationMs: 262000,
    durationSec: 262,
    coverUrl: "https://c.saavncdn.com/264/Aashiqui-2-Hindi-2013-500x500.jpg",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Romantic", "Indian Music"],
    subgenre: "Bollywood Romantic",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ROMANTIC]: 0.96,
      [MOODS.EMOTIONAL]: 0.90,
      [MOODS.SAD]: 0.65,
      [MOODS.MELANCHOLY]: 0.55
    },
    acousticFeatures: {
      energy: 0.48,
      valence: 0.42,
      danceability: 0.45,
      acousticness: 0.66,
      instrumentalness: 0.01,
      tempo: 92,
      popularity: 0.98
    },
    playsCount: 8900000,
    likesCount: 810000,
    isLiked: true,
    lyrics: "Kyunki tum hi ho ab tum hi ho zindagi ab tum hi ho...",
    explicit: false
  },
  // 4. Tera Ban Jaunga
  {
    id: "track_tera_ban_jaunga",
    title: "Tera Ban Jaunga",
    normalizedTitle: "tera ban jaunga",
    artist: "Akhil Sachdeva, Tulsi Kumar",
    artists: ["Akhil Sachdeva", "Tulsi Kumar"],
    artistIds: [],
    album: "Kabir Singh",
    albumId: "album_kabir_singh",
    movie: "Kabir Singh",
    movieId: "movie_kabir_singh",
    year: 2019,
    releaseDate: "2019-06-17",
    durationMs: 236000,
    durationSec: 236,
    coverUrl: "https://c.saavncdn.com/352/Kabir-Singh-Hindi-2019-20240130132014-500x500.jpg",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Romantic"],
    subgenre: "Bollywood Romantic",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ROMANTIC]: 0.92,
      [MOODS.HAPPY]: 0.72,
      [MOODS.EMOTIONAL]: 0.78
    },
    acousticFeatures: {
      energy: 0.56,
      valence: 0.74,
      danceability: 0.58,
      acousticness: 0.54,
      instrumentalness: 0.0,
      tempo: 104,
      popularity: 0.91
    },
    playsCount: 4700000,
    likesCount: 380000,
    isLiked: false,
    lyrics: "Meri raahein tere tak hain tujhpe hi toh mera haq hai...",
    explicit: false
  },
  // 5. Shayad
  {
    id: "track_shayad",
    title: "Shayad",
    normalizedTitle: "shayad",
    artist: "Arijit Singh, Pritam",
    artists: ["Arijit Singh", "Pritam"],
    artistIds: ["artist_arijit_singh", "artist_pritam"],
    album: "Love Aaj Kal",
    albumId: "album_love_aaj_kal",
    movie: "Love Aaj Kal",
    movieId: "movie_love_aaj_kal",
    year: 2020,
    releaseDate: "2020-01-22",
    durationMs: 247000,
    durationSec: 247,
    coverUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Romantic"],
    subgenre: "Bollywood Romantic",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ROMANTIC]: 0.91,
      [MOODS.EMOTIONAL]: 0.85,
      [MOODS.CHILL]: 0.65
    },
    acousticFeatures: {
      energy: 0.49,
      valence: 0.62,
      danceability: 0.52,
      acousticness: 0.60,
      instrumentalness: 0.01,
      tempo: 95,
      popularity: 0.92
    },
    playsCount: 4500000,
    likesCount: 390000,
    isLiked: true,
    lyrics: "Shayad kabhi na keh sakoon main tumko...",
    explicit: false
  },
  // 6. Khairiyat
  {
    id: "track_khairiyat",
    title: "Khairiyat",
    normalizedTitle: "khairiyat",
    artist: "Arijit Singh, Pritam",
    artists: ["Arijit Singh", "Pritam"],
    artistIds: ["artist_arijit_singh", "artist_pritam"],
    album: "Chhichhore",
    albumId: "album_chhichhore",
    movie: "Chhichhore",
    movieId: "movie_chhichhore",
    year: 2019,
    releaseDate: "2019-09-01",
    durationMs: 280000,
    durationSec: 280,
    coverUrl: "https://images.unsplash.com/photo-1445985543468-79abfeae063b?w=600&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Romantic", "Bollywood Sad"],
    subgenre: "Bollywood Romantic",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ROMANTIC]: 0.90,
      [MOODS.EMOTIONAL]: 0.92,
      [MOODS.SAD]: 0.60,
      [MOODS.NOSTALGIC]: 0.75
    },
    acousticFeatures: {
      energy: 0.50,
      valence: 0.58,
      danceability: 0.50,
      acousticness: 0.64,
      instrumentalness: 0.0,
      tempo: 96,
      popularity: 0.93
    },
    playsCount: 5100000,
    likesCount: 440000,
    isLiked: true,
    lyrics: "Khairiyat pucho kabhi to kaifiyat pucho...",
    explicit: false
  },
  // 7. Ranjha
  {
    id: "track_ranjha",
    title: "Ranjha",
    normalizedTitle: "ranjha",
    artist: "B Praak, Jasleen Royal",
    artists: ["B Praak", "Jasleen Royal"],
    artistIds: [],
    album: "Shershaah",
    albumId: "album_shershaah",
    movie: "Shershaah",
    movieId: "movie_shershaah",
    year: 2021,
    releaseDate: "2021-08-05",
    durationMs: 228000,
    durationSec: 228,
    coverUrl: "https://c.saavncdn.com/238/Shershaah-Original-Motion-Picture-Soundtrack-Hindi-2021-20210815181610-500x500.jpg",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Romantic", "Punjabi Pop"],
    subgenre: "Bollywood Romantic",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ROMANTIC]: 0.92,
      [MOODS.EMOTIONAL]: 0.88,
      [MOODS.CHILL]: 0.68
    },
    acousticFeatures: {
      energy: 0.46,
      valence: 0.55,
      danceability: 0.52,
      acousticness: 0.70,
      instrumentalness: 0.0,
      tempo: 90,
      popularity: 0.94
    },
    playsCount: 6200000,
    likesCount: 530000,
    isLiked: false,
    lyrics: "Ranjha ve ranjha ve main toh ranjha...",
    explicit: false
  },
  // 8. Apna Bana Le
  {
    id: "track_apna_bana_le",
    title: "Apna Bana Le",
    normalizedTitle: "apna bana le",
    artist: "Arijit Singh, Sachin-Jigar",
    artists: ["Arijit Singh", "Sachin-Jigar"],
    artistIds: ["artist_arijit_singh"],
    album: "Bhediya",
    albumId: "album_bhediya",
    movie: "Bhediya",
    movieId: "movie_bhediya",
    year: 2022,
    releaseDate: "2022-11-07",
    durationMs: 261000,
    durationSec: 261,
    coverUrl: "https://images.unsplash.com/photo-1445985543468-79abfeae063b?w=600&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Romantic"],
    subgenre: "Bollywood Romantic",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ROMANTIC]: 0.94,
      [MOODS.EMOTIONAL]: 0.86,
      [MOODS.HAPPY]: 0.76
    },
    acousticFeatures: {
      energy: 0.55,
      valence: 0.78,
      danceability: 0.50,
      acousticness: 0.62,
      instrumentalness: 0.0,
      tempo: 98,
      popularity: 0.95
    },
    playsCount: 5900000,
    likesCount: 520000,
    isLiked: true,
    lyrics: "Tu mera koi na hoke bhi kuch laage...",
    explicit: false
  },
  // 9. Kesariya
  {
    id: "track_kesariya",
    title: "Kesariya",
    normalizedTitle: "kesariya",
    artist: "Arijit Singh, Pritam",
    artists: ["Arijit Singh", "Pritam"],
    artistIds: ["artist_arijit_singh", "artist_pritam"],
    album: "Brahmāstra",
    albumId: "album_brahmastra",
    movie: "Brahmāstra: Part One – Shiva",
    movieId: "movie_brahmastra",
    year: 2022,
    releaseDate: "2022-07-17",
    durationMs: 268000,
    durationSec: 268,
    coverUrl: "https://c.saavncdn.com/007/Brahmastra-Hindi-2022-20221006180034-500x500.jpg",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Romantic", "Bollywood Melodic"],
    subgenre: "Bollywood Romantic",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ROMANTIC]: 0.95,
      [MOODS.HAPPY]: 0.85,
      [MOODS.EMOTIONAL]: 0.75
    },
    acousticFeatures: {
      energy: 0.62,
      valence: 0.85,
      danceability: 0.58,
      acousticness: 0.45,
      instrumentalness: 0.0,
      tempo: 110,
      popularity: 0.99
    },
    playsCount: 9200000,
    likesCount: 880000,
    isLiked: true,
    lyrics: "Kesariya tera ishq hai piya rang jaaun jo main haath lagaun...",
    explicit: false
  },
  // 10. Satranga
  {
    id: "track_satranga",
    title: "Satranga",
    normalizedTitle: "satranga",
    artist: "Arijit Singh, Shreyas Puranik",
    artists: ["Arijit Singh", "Shreyas Puranik"],
    artistIds: ["artist_arijit_singh"],
    album: "Animal",
    albumId: "album_animal",
    movie: "Animal",
    movieId: "movie_animal",
    year: 2023,
    releaseDate: "2023-10-27",
    durationMs: 271000,
    durationSec: 271,
    coverUrl: "https://c.saavncdn.com/092/ANIMAL-Hindi-2023-20231124191438-500x500.jpg",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Romantic", "Bollywood Emotional"],
    subgenre: "Bollywood Romantic",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ROMANTIC]: 0.88,
      [MOODS.EMOTIONAL]: 0.94,
      [MOODS.SAD]: 0.62,
      [MOODS.MELANCHOLY]: 0.70
    },
    acousticFeatures: {
      energy: 0.54,
      valence: 0.45,
      danceability: 0.48,
      acousticness: 0.58,
      instrumentalness: 0.01,
      tempo: 94,
      popularity: 0.97
    },
    playsCount: 7800000,
    likesCount: 720000,
    isLiked: true,
    lyrics: "Adhoore se the hum poore huye...",
    explicit: false
  },
  // 11. Dhurandhar Title Track (Movie: Dhurandhar)
  {
    id: "track_dhurandhar_title",
    title: "Dhurandhar Title Track",
    normalizedTitle: "dhurandhar title track",
    artist: "Shashwat Sachdev, B Praak",
    artists: ["Shashwat Sachdev", "B Praak"],
    artistIds: [],
    album: "Dhurandhar",
    albumId: "album_dhurandhar",
    movie: "Dhurandhar",
    movieId: "movie_dhurandhar",
    year: 2025,
    releaseDate: "2025-10-01",
    durationMs: 215000,
    durationSec: 215,
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Action", "Indian Music"],
    subgenre: "Bollywood Action",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ENERGETIC]: 0.96,
      [MOODS.MOTIVATIONAL]: 0.92,
      [MOODS.WORKOUT]: 0.88,
      [MOODS.PATRIOTIC]: 0.85
    },
    acousticFeatures: {
      energy: 0.92,
      valence: 0.65,
      danceability: 0.70,
      acousticness: 0.12,
      instrumentalness: 0.05,
      tempo: 138,
      popularity: 0.94
    },
    playsCount: 3400000,
    likesCount: 310000,
    isLiked: true,
    lyrics: "Sher jaisa jigar leke aag pe chalna hai...",
    explicit: false
  },
  // 12. Jazbaat (Dhurandhar)
  {
    id: "track_dhurandhar_jazbaat",
    title: "Jazbaat",
    normalizedTitle: "jazbaat",
    artist: "Arijit Singh, Shashwat Sachdev",
    artists: ["Arijit Singh", "Shashwat Sachdev"],
    artistIds: ["artist_arijit_singh"],
    album: "Dhurandhar",
    albumId: "album_dhurandhar",
    movie: "Dhurandhar",
    movieId: "movie_dhurandhar",
    year: 2025,
    releaseDate: "2025-10-05",
    durationMs: 255000,
    durationSec: 255,
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Romantic"],
    subgenre: "Bollywood Romantic",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ROMANTIC]: 0.93,
      [MOODS.EMOTIONAL]: 0.89,
      [MOODS.CHILL]: 0.65
    },
    acousticFeatures: {
      energy: 0.51,
      valence: 0.64,
      danceability: 0.53,
      acousticness: 0.62,
      instrumentalness: 0.01,
      tempo: 96,
      popularity: 0.91
    },
    playsCount: 2800000,
    likesCount: 260000,
    isLiked: true,
    lyrics: "Mere jazbaaton mein shaamil ho tum...",
    explicit: false
  },
  // 13. Aag Ka Dariya (Dhurandhar)
  {
    id: "track_dhurandhar_aag",
    title: "Aag Ka Dariya",
    normalizedTitle: "aag ka dariya",
    artist: "Vishal Dadlani, Shashwat Sachdev",
    artists: ["Vishal Dadlani", "Shashwat Sachdev"],
    artistIds: [],
    album: "Dhurandhar",
    albumId: "album_dhurandhar",
    movie: "Dhurandhar",
    movieId: "movie_dhurandhar",
    year: 2025,
    releaseDate: "2025-10-10",
    durationMs: 202000,
    durationSec: 202,
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Action", "Indian Rock"],
    subgenre: "Bollywood Action",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ENERGETIC]: 0.95,
      [MOODS.WORKOUT]: 0.90,
      [MOODS.MOTIVATIONAL]: 0.88
    },
    acousticFeatures: {
      energy: 0.94,
      valence: 0.58,
      danceability: 0.66,
      acousticness: 0.08,
      instrumentalness: 0.04,
      tempo: 142,
      popularity: 0.87
    },
    playsCount: 1950000,
    likesCount: 180000,
    isLiked: false,
    lyrics: "Aag ka dariya doob ke jaana...",
    explicit: false
  },
  // 14. Brown Munde (Punjabi / Party)
  {
    id: "track_brown_munde",
    title: "Brown Munde",
    normalizedTitle: "brown munde",
    artist: "AP Dhillon, Gurinder Gill, Shinda Kahlon",
    artists: ["AP Dhillon", "Gurinder Gill", "Shinda Kahlon"],
    artistIds: ["artist_ap_dhillon"],
    album: "Not by Chance",
    albumId: "album_not_by_chance",
    movie: null,
    movieId: null,
    year: 2020,
    releaseDate: "2020-09-18",
    durationMs: 266000,
    durationSec: 266,
    coverUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    genre: "Punjabi",
    genres: ["Punjabi", "Punjabi Hip-Hop", "Punjabi Pop"],
    subgenre: "Punjabi Hip-Hop",
    language: "Punjabi",
    primaryLanguage: "Punjabi",
    moods: {
      [MOODS.PARTY]: 0.95,
      [MOODS.ENERGETIC]: 0.90,
      [MOODS.WORKOUT]: 0.85,
      [MOODS.DANCE]: 0.88
    },
    acousticFeatures: {
      energy: 0.85,
      valence: 0.72,
      danceability: 0.88,
      acousticness: 0.15,
      instrumentalness: 0.0,
      tempo: 124,
      popularity: 0.96
    },
    playsCount: 8400000,
    likesCount: 790000,
    isLiked: false,
    lyrics: "Khande peende ghumde firde desi munde...",
    explicit: false
  },
  // 15. Lover (Punjabi / Party / Pop)
  {
    id: "track_lover",
    title: "Lover",
    normalizedTitle: "lover",
    artist: "Diljit Dosanjh, Intense",
    artists: ["Diljit Dosanjh", "Intense"],
    artistIds: ["artist_diljit_dosanjh"],
    album: "MoonChild Era",
    albumId: "album_moonchild_era",
    movie: null,
    movieId: null,
    year: 2021,
    releaseDate: "2021-08-22",
    durationMs: 198000,
    durationSec: 198,
    coverUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    genre: "Punjabi",
    genres: ["Punjabi", "Punjabi Pop", "Dance Pop"],
    subgenre: "Punjabi Pop",
    language: "Punjabi",
    primaryLanguage: "Punjabi",
    moods: {
      [MOODS.PARTY]: 0.92,
      [MOODS.HAPPY]: 0.94,
      [MOODS.DANCE]: 0.95,
      [MOODS.ROMANTIC]: 0.70
    },
    acousticFeatures: {
      energy: 0.88,
      valence: 0.89,
      danceability: 0.92,
      acousticness: 0.10,
      instrumentalness: 0.0,
      tempo: 118,
      popularity: 0.93
    },
    playsCount: 6500000,
    likesCount: 610000,
    isLiked: false,
    lyrics: "Tera ni main lover tera ni main lover...",
    explicit: false
  },
  // 16. Starboy (Global Pop / Electropop)
  {
    id: "track_starboy",
    title: "Starboy",
    normalizedTitle: "starboy",
    artist: "The Weeknd, Daft Punk",
    artists: ["The Weeknd", "Daft Punk"],
    artistIds: ["artist_the_weeknd"],
    album: "Starboy",
    albumId: "album_starboy",
    movie: null,
    movieId: null,
    year: 2016,
    releaseDate: "2016-09-21",
    durationMs: 230000,
    durationSec: 230,
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    genre: "Electropop",
    genres: ["Global Music", "Electropop", "R&B"],
    subgenre: "Electropop",
    language: "English",
    primaryLanguage: "English",
    moods: {
      [MOODS.PARTY]: 0.88,
      [MOODS.ENERGETIC]: 0.84,
      [MOODS.DANCE]: 0.85
    },
    acousticFeatures: {
      energy: 0.82,
      valence: 0.65,
      danceability: 0.78,
      acousticness: 0.12,
      instrumentalness: 0.0,
      tempo: 186,
      popularity: 0.95
    },
    playsCount: 14500000,
    likesCount: 1200000,
    isLiked: false,
    lyrics: "I'm tryna put you in the worst mood ah...",
    explicit: true
  },
  // 17. Blinding Lights (Synthwave / Dance)
  {
    id: "track_blinding_lights",
    title: "Blinding Lights",
    normalizedTitle: "blinding lights",
    artist: "The Weeknd",
    artists: ["The Weeknd"],
    artistIds: ["artist_the_weeknd"],
    album: "After Hours",
    albumId: "album_after_hours",
    movie: null,
    movieId: null,
    year: 2020,
    releaseDate: "2019-11-29",
    durationMs: 200000,
    durationSec: 200,
    coverUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    genre: "Synthwave",
    genres: ["Global Music", "Synthwave", "Dance Pop"],
    subgenre: "Synthwave",
    language: "English",
    primaryLanguage: "English",
    moods: {
      [MOODS.ENERGETIC]: 0.94,
      [MOODS.DANCE]: 0.92,
      [MOODS.WORKOUT]: 0.88,
      [MOODS.HAPPY]: 0.80
    },
    acousticFeatures: {
      energy: 0.91,
      valence: 0.72,
      danceability: 0.85,
      acousticness: 0.05,
      instrumentalness: 0.0,
      tempo: 171,
      popularity: 0.99
    },
    playsCount: 22000000,
    likesCount: 1950000,
    isLiked: false,
    lyrics: "I've been tryna call I've been on my own for long enough...",
    explicit: false
  },
  // 18. Levitating (Disco Pop)
  {
    id: "track_levitating",
    title: "Levitating",
    normalizedTitle: "levitating",
    artist: "Dua Lipa",
    artists: ["Dua Lipa"],
    artistIds: ["artist_dua_lipa"],
    album: "Future Nostalgia",
    albumId: "album_future_nostalgia",
    movie: null,
    movieId: null,
    year: 2020,
    releaseDate: "2020-03-27",
    durationMs: 203000,
    durationSec: 203,
    coverUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    genre: "Disco Pop",
    genres: ["Global Music", "Disco Pop", "Dance Pop"],
    subgenre: "Disco Pop",
    language: "English",
    primaryLanguage: "English",
    moods: {
      [MOODS.PARTY]: 0.95,
      [MOODS.HAPPY]: 0.96,
      [MOODS.DANCE]: 0.98,
      [MOODS.WORKOUT]: 0.82
    },
    acousticFeatures: {
      energy: 0.88,
      valence: 0.90,
      danceability: 0.92,
      acousticness: 0.08,
      instrumentalness: 0.0,
      tempo: 103,
      popularity: 0.97
    },
    playsCount: 16000000,
    likesCount: 1400000,
    isLiked: false,
    lyrics: "If you wanna run away with me I know a galaxy...",
    explicit: false
  },
  // 19. Husn (Indie Acoustic)
  {
    id: "track_husn",
    title: "Husn",
    normalizedTitle: "husn",
    artist: "Anuv Jain",
    artists: ["Anuv Jain"],
    artistIds: ["artist_anuv_jain"],
    album: "Husn - Single",
    albumId: "album_husn",
    movie: null,
    movieId: null,
    year: 2023,
    releaseDate: "2023-12-01",
    durationMs: 217000,
    durationSec: 217,
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    genre: "Indie Acoustic",
    genres: ["Indian Music", "Indie Acoustic", "Indie Folk"],
    subgenre: "Indie Acoustic",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.CHILL]: 0.92,
      [MOODS.EMOTIONAL]: 0.95,
      [MOODS.MELANCHOLY]: 0.88,
      [MOODS.LOFI]: 0.78,
      [MOODS.SAD]: 0.75
    },
    acousticFeatures: {
      energy: 0.35,
      valence: 0.45,
      danceability: 0.42,
      acousticness: 0.88,
      instrumentalness: 0.02,
      tempo: 92,
      popularity: 0.94
    },
    playsCount: 5800000,
    likesCount: 520000,
    isLiked: true,
    lyrics: "Dekho dekho kaise baatein yahan ki...",
    explicit: false
  },
  // 20. Tujhe Dekha Toh (90s Bollywood Retro Romance)
  {
    id: "track_tujhe_dekha_toh",
    title: "Tujhe Dekha Toh",
    normalizedTitle: "tujhe dekha toh",
    artist: "Kumar Sanu, Lata Mangeshkar, Jatin-Lalit",
    artists: ["Kumar Sanu", "Lata Mangeshkar", "Jatin-Lalit"],
    artistIds: [],
    album: "Dilwale Dulhania Le Jayenge",
    albumId: "album_ddlj",
    movie: "Dilwale Dulhania Le Jayenge",
    movieId: "movie_ddlj",
    year: 1995,
    releaseDate: "1995-10-20",
    durationMs: 302000,
    durationSec: 302,
    coverUrl: "https://c.saavncdn.com/264/Dilwale-Dulhania-Le-Jayenge-Hindi-1995-500x500.jpg",
    streamUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    losslessUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    genre: "Bollywood",
    genres: ["Bollywood", "Bollywood Retro", "Bollywood Romantic"],
    subgenre: "Bollywood Retro",
    language: "Hindi",
    primaryLanguage: "Hindi",
    moods: {
      [MOODS.ROMANTIC]: 0.98,
      [MOODS.NOSTALGIC]: 0.96,
      [MOODS.HAPPY]: 0.82
    },
    acousticFeatures: {
      energy: 0.52,
      valence: 0.76,
      danceability: 0.56,
      acousticness: 0.65,
      instrumentalness: 0.01,
      tempo: 98,
      popularity: 0.96
    },
    playsCount: 12000000,
    likesCount: 990000,
    isLiked: true,
    lyrics: "Tujhe dekha toh ye jaana sanam pyaar hota hai deewana sanam...",
    explicit: false
  }
];

const playlists = [
  {
    id: "pl_today_hits",
    title: "Today's Top Hits",
    description: "The hottest tracks right now across India and globally.",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80",
    trackCount: tracks.length,
    tracks: tracks.map(t => t.id),
    isCurated: true
  },
  {
    id: "pl_romantic_bollywood",
    title: "Romantic Bollywood Gold",
    description: "Soulful Bollywood love ballads and acoustic serenades.",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80",
    trackCount: 10,
    tracks: ["track_hawayein", "track_tum_hi_ho", "track_agar_tum", "track_kesariya", "track_apna_bana_le", "track_shayad", "track_khairiyat"],
    isCurated: true
  },
  {
    id: "pl_punjabi_fire",
    title: "Punjabi Party Anthem",
    description: "Electrifying bhangra beats and viral Punjabi club hits.",
    coverUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80",
    trackCount: 8,
    tracks: ["track_brown_munde", "track_lover"],
    isCurated: true
  }
];

module.exports = {
  movies,
  artists,
  albums,
  tracks,
  playlists
};
